# Travis CI Configuration

language: node_js
node_js:
  - "12"
  - "11"
  - "10"
  - "9"
  - "8"
install:
  - npm install
  - npm install coveralls
before_script:
  - ./node_modules/brunch/bin/brunch build
script:
  - npm run lint
  - npm run coverage
after_success:
  - cat coverage/lcov.info | coveralls
